version: "3.5"

networks:
  net_lb:
    external: true

services:
  magneto:
    image: hugoseabra19/xmen-magneto-ambition:latest
    restart: unless-stopped
    hostname: magneto
    env_file: ../../../.env
    ports:
      - "8000"
    networks:
      - net_lb
    volumes:
      - ../../../shared-volume/media:/code/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magneto.rule=Host(`magneto.hugoseabra.space`)"
      - "traefik.http.routers.magneto.entrypoints=web"
      - "traefik.protocol=http"
      - "traefik.docker.network=net_lb"
      - "traefik.frontend.passHostHeader=true"
